### DISCUSSION TITLE
Monitoring Heat Pump Energy Usage Per State

### DISCUSSION THREAD

**Discussion by misteriks** [BenPru/luxtronik#354] [Show and tell]
Hi all,

My Luxtronik-controlled heat pump (in Dutch: warmtepomp) doesn't natively report its energy consumption statistics, which made it hard to understand its impact on our overall electricity usage. To get more detailed insights, I decided to install a [Shelly 3EM-63W Gen3](https://www.shelly.com/products/shelly-3em-63w-gen3?variant=56273492771165) directly onto the heat pump's 3-phase circuit breaker.

If someone is going to do the same then make sure to keep the phase wires in the same order otherwise your heat pump might give the error _"751 - Phase monitoring fault. Phase-sequence relay has responded. Check rotary field and phase-sequence relay"_

Here's a picture of the Shelly installed in the distribution box:
![image](https://github.com/user-attachments/assets/37df6337-edc0-42ac-98b3-88563aa94c75)

My main goal is to break down the heat pump's energy consumption based on its different operating states (like heating, cooling, domestic hot water, defrosting, etc.) and track these individually within the Home Assistant Energy Dashboard.

To achieve this, I set up the following in Home Assistant:

**1. Total Power Measurement:** The Shelly 3EM (sensor.energymonitor_warmtepomp_total_active_power) provides the overall instantaneous power draw of the heat pump.

**2. Heat Pump State:** The Luxtronik integration gives me the current operational status via sensor.luxtronik_220131_0144_status_line_3 (e.g., heating, cooling, domestic water, defrost, thermal desinfection, no request).

**3. State-Specific Power Sensors (Templates)**: I created several template sensors in templates.yaml. Each sensor corresponds to a specific heat pump state. For example, the "Warmtepomp Vermogen Verwarming" (Heat Pump Power Heating) sensor checks if the Luxtronik status is heating. If it is, this sensor's value becomes the total power reported by the Shelly 3EM; otherwise, it's set to 0 W. I replicated this logic for cooling, domestic water, defrost, thermal disinfection, no request, and created a final "catch-all" sensor for any other states.

**4. Energy Accumulation Sensors (Integration):** For each of the power template sensors created above, I added a corresponding Riemann sum integration sensor in sensors.yaml. These sensors calculate the energy consumed (in kWh) for each specific state over time (e.g., sensor.warmtepomp_energie_verwarming), making them perfect for the Energy Dashboard.

This configuration allows me to add each function (Heating, Cooling, Hot Water, etc.) as a separate consumable device in the HA Energy Dashboard, giving a much clearer picture of where the energy is going.

Our household electricity usage seems quite high, and I'm keen to understand the heat pump's contribution better. My first step is to gather this detailed data to establish a baseline. Once I have a clearer understanding, I want to explore opportunities to optimize its operation and potentially reduce consumption.

I'm still exploring the possibilities with the Luxtronik integration and this energy monitoring setup.

I'd love to hear from others:
Are you doing something similar with your Luxtronik heat pumps? How are you monitoring energy usage, especially if you're breaking it down by operational state? Any tips or different approaches for gaining insights or optimizing performance based on the Luxtronik data?

Thanks for sharing your experiences!

Below are the entries I created in Home Assistant

**Templates.yaml**

```yaml
- sensor:
  - name: "Warmtepomp Vermogen Verwarming"
    unique_id: cc63a9f6-ed69-41e9-9235-db219a1dc1d0
    state: >
      {% if is_state('sensor.luxtronik_220131_0144_status_line_3', 'heating') %}
        {{ states('sensor.energymonitor_warmtepomp_total_active_power') | float(0) }}
      {% else %}
        0
      {% endif %}
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    availability: >
      {{ states('sensor.energymonitor_warmtepomp_total_active_power') not in ['unknown', 'unavailable'] and
          states('sensor.luxtronik_220131_0144_status_line_3') not in ['unknown', 'unavailable'] }}

  - name: "Warmtepomp Vermogen Koelen"
    unique_id: 33e52a52-2751-4f92-965b-0cc5f4fb496b
    state: >
      {% if is_state('sensor.luxtronik_220131_0144_status_line_3', 'cooling') %}
        {{ states('sensor.energymonitor_warmtepomp_total_active_power') | float(0) }}
      {% else %}
        0
      {% endif %}
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    availability: >
      {{ states('sensor.energymonitor_warmtepomp_total_active_power') not in ['unknown', 'unavailable'] and
          states('sensor.luxtronik_220131_0144_status_line_3') not in ['unknown', 'unavailable'] }}

  - name: "Warmtepomp Vermogen Warm Water"
    unique_id: 38875a27-3388-40af-872d-38fcc05a6daf
    state: >
      {% if is_state('sensor.luxtronik_220131_0144_status_line_3', 'domestic water') %}
        {{ states('sensor.energymonitor_warmtepomp_total_active_power') | float(0) }}
      {% else %}
        0
      {% endif %}
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    availability: >
      {{ states('sensor.energymonitor_warmtepomp_total_active_power') not in ['unknown', 'unavailable'] and
          states('sensor.luxtronik_220131_0144_status_line_3') not in ['unknown', 'unavailable'] }}

  - name: "Warmtepomp Vermogen Ontdooien"
    unique_id: 4f2060d3-d294-4078-a58d-affab966850b
    state: >
      {% if is_state('sensor.luxtronik_220131_0144_status_line_3', 'defrost') %}
        {{ states('sensor.energymonitor_warmtepomp_total_active_power') | float(0) }}
      {% else %}
        0
      {% endif %}
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    availability: >
      {{ states('sensor.energymonitor_warmtepomp_total_active_power') not in ['unknown', 'unavailable'] and
          states('sensor.luxtronik_220131_0144_status_line_3') not in ['unknown', 'unavailable'] }}
  
  - name: "Warmtepomp Vermogen Thermische Desinfectie"
    unique_id: 48399371-ef8e-416d-8293-8cd5dd2a1d31
    state: >
      {% if is_state('sensor.luxtronik_220131_0144_status_line_3', 'thermal desinfection') %}
        {{ states('sensor.energymonitor_warmtepomp_total_active_power') | float(0) }}
      {% else %}
        0
      {% endif %}
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    availability: >
      {{ states('sensor.energymonitor_warmtepomp_total_active_power') not in ['unknown', 'unavailable'] and
          states('sensor.luxtronik_220131_0144_status_line_3') not in ['unknown', 'unavailable'] }}

  - name: "Warmtepomp Vermogen Geen Vraag"
    unique_id: 787e44ba-a861-437e-84b8-acbb58999335
    state: >
      {% if is_state('sensor.luxtronik_220131_0144_status_line_3', 'no request') %}
        {{ states('sensor.energymonitor_warmtepomp_total_active_power') | float(0) }}
      {% else %}
        0
      {% endif %}
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    availability: >
      {{ states('sensor.energymonitor_warmtepomp_total_active_power') not in ['unknown', 'unavailable'] and
          states('sensor.luxtronik_220131_0144_status_line_3') not in ['unknown', 'unavailable'] }}

  - name: "Warmtepomp Vermogen Overig"
    unique_id: 01324ec2-1ca9-4cdc-a127-1b0f0f4fe01b
    state: >
      {% set known_states = [
            'heating',
            'cooling',
            'domestic water',
            'defrost',
            'thermal desinfection',
            'no request'
          ] %}
      {% if states('sensor.luxtronik_220131_0144_status_line_3') not in known_states %}
        {{ states('sensor.energymonitor_warmtepomp_total_active_power') | float(0) }}
      {% else %}
        0
      {% endif %}
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    availability: >
      {{ states('sensor.energymonitor_warmtepomp_total_active_power') not in ['unknown', 'unavailable'] and
          states('sensor.luxtronik_220131_0144_status_line_3') not in ['unknown', 'unavailable'] }}
```

**sensors.yaml** 

```yaml

- platform: integration
  source: sensor.warmtepomp_vermogen_verwarming
  name: Warmtepomp Energie Verwarming
  unique_id: 09a2b0e3-db2d-4c94-8b38-d6255ce65fa3
  unit_prefix: k
  unit_time: h
  round: 2

- platform: integration
  source: sensor.warmtepomp_vermogen_koelen
  name: Warmtepomp Energie Koelen
  unique_id: 67bf6408-687b-4989-ad11-45202031d2ff
  unit_prefix: k
  unit_time: h
  round: 2

- platform: integration
  source: sensor.warmtepomp_vermogen_warm_water
  name: Warmtepomp Energie Warm Water
  unique_id: 4adddc51-8e32-4924-ae55-e697d22c43cf
  unit_prefix: k
  unit_time: h
  round: 2

- platform: integration
  source: sensor.warmtepomp_vermogen_ontdooien
  name: Warmtepomp Energie Ontdooien
  unique_id: 0aa13cf6-e383-4e58-91e2-d66e29a86479
  unit_prefix: k
  unit_time: h
  round: 2

- platform: integration
  source: sensor.warmtepomp_vermogen_geen_vraag
  name: Warmtepomp Energie Geen Vraag
  unique_id: 16196d3f-350b-403a-838b-be43b6467e96
  unit_prefix: k
  unit_time: h
  round: 2
  
- platform: integration
  source: sensor.warmtepomp_vermogen_thermische_desinfectie
  name: Warmtepomp Energie Thermische Desinfectie
  unique_id: 4fefcdf4-373e-46a2-9eec-f40bd6487767
  unit_prefix: k
  unit_time: h
  round: 2

- platform: integration
  source: sensor.warmtepomp_vermogen_overig
  name: Warmtepomp Energie Overig
  unique_id: a1eab39b-6839-437b-a6f1-2c737f1c5969
  unit_prefix: k
  unit_time: h
  round: 2

```

**Comment by AJediIAm** [comment]
The advanced configurations https://www.home-assistant.io/integrations/utility_meter/ describes how to use an automation and utility meter helper to split an energy sensor into several energy sensors based on the state.

Through arcane magic, an hourly and daily sensor is created per state.

Helper:
```
utility_meter:
  heatpump_energy_hourly:
    source: sensor.energy
    name: Daily Energy
    cycle: daily
    tariffs:
      - heat
      - cool
      - idle
      - dhw
  heatpump_energy_daily:
    source: sensor.energy
    name: Monthly Energy
    cycle: monthly
    tariffs:
      - heat
      - cool
      - idle
      - dhw
```

Automation:
```
alias: Heatpump - Energy tariff
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.luxtronik_status
    to: Heating
    variables:
      tariff: heat
  - trigger: state
    entity_id:
      - sensor.luxtronik_status
    to: Domestic Water
    variables:
      tariff: dhw
  - trigger: state
    entity_id:
      - sensor.luxtronik_status
    to: Idle
    variables:
      tariff: idle
  - trigger: state
    entity_id:
      - sensor.luxtronik_status
    to: Cooling
    variables:
      tariff: cool
actions:
  - action: select.select_option
    target:
      entity_id: select.heatpump_energy_daily
    data:
      option: "{{ tariff }}"
  - action: select.select_option
    target:
      entity_id: select.heatpump_energy_hourly
    data:
      option: "{{ tariff }}"
mode: single
```

It should work, but I still have some issues with it. 
Maybe I need to use lower cases for the states. 
Maybe I need to use YAML instead of using the UI.
Or maybe it is because the status isn't very stable:
![image](https://github.com/user-attachments/assets/b295d7a6-20b3-4a55-9f9c-d69436f2ca07)
