### ISSUE TITLE
Will it never be possible to config in yaml my sensors in 2023.9.12-Alpha-Core-Preview

### ISSUE THREAD

**Issue by colognebroker** [BenPru/luxtronik#129]
I allways configured in configuration.yaml some luxtronik devices in addition !
In the Alpha core it is not possible, also in future ?

**Comment by BenPru** [comment]
No. The ha guys want all configs as GUI config.
Which Sensors do you need?
We can implement them her as normal sensor.
Or you create them and create a pr: https://github.com/BenPru/luxtronik/blob/core-preview/custom_components/luxtronik/sensor_entities_predefined.py

**Comment by colognebroker** [comment]
ID_WEB_Durchfluss_WQ

**Comment by colognebroker** [comment]
ID_WEB_Durchfluss_WQ
This is flow per liter from sole pump

**Comment by Kars-de-Jong** [comment]
Actually, this is the flow in l/h in the heating circuit (HUP), not the VBO circuit.
And yes, I would like to see this sensor by default.

I have several more sensors configured, relating to the temperature delta's of the regulation.

```yaml
    - name: "VBO delta calculated"
      unique_id: "ait_hup_vbo_calculated"
      state: "{{ states('sensor.luxtronik2_unknown_calculation_239')|float / 10 }}"
      availability: "{{ states('sensor.luxtronik2_unknown_calculation_239') != None }}"
      unit_of_measurement: K
      state_class: measurement
      icon: mdi:delta
    - name: "VBO delta"
      unique_id: "ait_vbo_delta"
      state: "{{ states('sensor.luxtronik2_unknown_calculation_240')|float / 10 }}"
      availability: "{{ states('sensor.luxtronik2_unknown_calculation_240') != None }}"
      unit_of_measurement: K
      state_class: measurement
      icon: mdi:delta
    - name: "HUP delta calculated"
      unique_id: "ait_hup_delta_calculated"
      state: "{{ states('sensor.luxtronik2_unknown_calculation_242')|float / 10 }}"
      availability: "{{ states('sensor.luxtronik2_unknown_calculation_242') != None }}"
      unit_of_measurement: K
      state_class: measurement
      icon: mdi:delta
    - name: "HUP delta"
      unique_id: "ait_hup_delta"
      state: "{{ states('sensor.luxtronik2_unknown_calculation_243')|float / 10 }}"
      availability: "{{ states('sensor.luxtronik2_unknown_calculation_243') != None }}"
      unit_of_measurement: K
      state_class: measurement
      icon: mdi:delta
```

As you can see I am using template sensors because I have to convert the raw values to float and divide the value by 10 to get the correct values, because the `luxtronik` Python package doesn't support them. They should really be added there, and given a proper name and type.
