### ISSUE TITLE
Room temperature sensor not available

### ISSUE THREAD

**Issue by Laars123** [BenPru/luxtronik#15]
My luxtronik/alpha innotec installation includes a room temperature sensor.
However, it doesn't show up in the integration. Can this be added?
It does show up in de webserver heatpump controller though.
Thanks!

Note: Auto discovery didn't work in my case.

**Comment by rhammen** [comment]
I'd also like to have this :-)
parameter: ID_WEB_RBE_RT_Ist

**Comment by rhammen** [comment]
I was able to add the Room Temperature by adding the following around line 400 of sensor.py:
            LuxtronikSensor(
                hass,
                luxtronik,
                device_info_heating,
                "calculations.ID_WEB_RBE_RT_Ist",
                "room_temperature",
                f"Room {text_temp}",
                entity_category=None,
            ),

Additionally, I added a sensor for the Pumpfrequency at around line 325 in sensor.py:
        LuxtronikSensor(
            hass,
            luxtronik,
            device_info,
            "calculations.ID_WEB_Freq_VD",
            "pump frequency",
            f"Pump Frequency",
            entity_category=None,
            icon="mdi:sine-wave",
            unit_of_measurement='Hz'
        ),

**Comment by Kars-de-Jong** [comment]
For the climate entity, you can add this yourself using the configuration dialog. Just enter “calculations.ID_WEB_RBE_RT_Ist” in the “Home Assistant sensor id for the current indoor temperature” text field.

@rhammen that is not the pump frequency, it’s the compressor frequency.

You can add extra sensors yourself using the “luxtronic2” sensor platform:

```yaml
sensors:
  - platform: luxtronik2
    sensors:
      - group: calculations
        id: ID_WEB_Temperatur_THG
        friendly_name: Temperatuur heetgas
        icon: mdi:thermometer
        state_class: measurement
      - group: calculations
        id: Heat_Output
        friendly_name: Vermogen
        icon: mdi:flash
        state_class: measurement
        unit_of_measurement: W
```
etc.
