### ISSUE TITLE
Add missing sensors for temperature delta on VBO and HUP

### ISSUE THREAD

**Issue by Kars-de-Jong** [BenPru/luxtronik#156]
As requested here, a new issue for adding these diagnostic sensors for the temperature delta on the VBO and HUP.

Below is my current template sensor configuration. There is no `device_class` for these sensors.
HUP is probably what you call `circulation_pump_heating`, although it is also used for DHW through the use of a three-way valve.
VBO is what you call `pump_flow`, in my case the brine pump.

```yaml
    - name: "VBO delta calculated"
      unique_id: "ait_vbo_delta_calculated"
      state: "{{ states('sensor.luxtronik2_unknown_calculation_239')|float / 10 }}"
      availability: "{{ states('sensor.luxtronik2_unknown_calculation_239') != None }}"
      unit_of_measurement: K
      state_class: measurement
      icon: mdi:delta
    - name: "VBO delta"
      unique_id: "ait_vbo_delta"
      state: "{{ states('sensor.luxtronik2_unknown_calculation_240')|float / 10 }}"
      availability: "{{ states('sensor.luxtronik2_unknown_calculation_240') != None }}"
      unit_of_measurement: K
      state_class: measurement
      icon: mdi:delta
    - name: "HUP delta calculated"
      unique_id: "ait_hup_delta_calculated"
      state: "{{ states('sensor.luxtronik2_unknown_calculation_242')|float / 10 }}"
      availability: "{{ states('sensor.luxtronik2_unknown_calculation_242') != None }}"
      unit_of_measurement: K
      state_class: measurement
      icon: mdi:delta
    - name: "HUP delta"
      unique_id: "ait_hup_delta"
      state: "{{ states('sensor.luxtronik2_unknown_calculation_243')|float / 10 }}"
      availability: "{{ states('sensor.luxtronik2_unknown_calculation_243') != None }}"
      unit_of_measurement: K
      state_class: measurement
      icon: mdi:delta
```

In the latest version of `luxtronik` these sensors are no longer unknown, so the division by 10 should no longer be needed.

```python
            239: Kelvin("VBO_Temp_Spread_Soll"),
            240: Kelvin("VBO_Temp_Spread_Ist"),
            241: Percent2("HUP_PWM"),
            242: Kelvin("HUP_Temp_Spread_Soll"),
            243: Kelvin("HUP_Temp_Spread_Ist"),
```
