### ISSUE TITLE
Frage: wie führe ich den Dienst "write" aus?

### ISSUE THREAD

**Issue by kroessig** [BenPru/luxtronik#210]
Hallo, 

ich habe den Bereich gelesen, aber ich bekomme es dennoch nicht hin:
Ich will eine Automatisierung starten, die den Wert "heating_target_correction" um 1 erhöht. Habe den Wert geändert und jeweils die Diagnostik-Files geladen und verglichen. Sollte der Parameter ID_Einst_WK_akt sein.

Unter Dienste (dort teste ich immer zuerst meine Dienste) hab ich folgendes geschrieben:

```
service: luxtronik2.write
data:
  parameter: ID_Einst_WK_akt
  value: "{{ float(states('number.luxtronik2_heating_target_correction')) + 1 }}"
```

Es kommt der Hinweis: "Die Benutzeroberfläche unterstützt keine Templates. Du kannst aber weiterhin den YAML-Editor verwenden."
Ich kann ausführen, grüner Haken, aber nichts passiert....

Unter Vorlage kommt bei "{{ float(states('number.luxtronik2_heating_target_correction')) + 1 }}" der richtige Wert raus.

Kann mir das jemand korrekt zusammenschrieben. Vielen Dank vorab!
