### ISSUE TITLE
Missing sensor MK1? (question)

### ISSUE THREAD

**Issue by sshknoll** [BenPru/luxtronik#285]
Hi everyone,

first of thank you very much for the work you are putting into this project! :)

I recently installed the integration in HomeAssistant and it works quite well. What I am missing is the sensor values for MK1 mixing circuit (MK1 target and current). Are these deliberately not included or am I missing something here?

Thanks for any hints on that!

**Comment by toggm** [comment]
Same problem here. Tried to add them manually, but without any luck:
```
- platform: luxtronik2
  sensors:
   - group: calculations
     id: ID_WEB_Temperatur_TFB1
     friendly_name: Mischkreis1-Vorlauf
     icon: mdi:thermometer
   - group: calculations
     id: ID_WEB_Temperatur_TFB2
     friendly_name: Mischkreis2-Vorlauf
     icon: mdi:thermometer
   - group: calculations
     id: ID_WEB_Sollwert_TVL_MK1
     friendly_name: Mischkreis1 VL-Soll
     icon: mdi:thermometer
   - group: calculations
     id: ID_WEB_Sollwert_TVL_MK2
     friendly_name: Mischkreis2 VL-Soll
     icon: mdi:thermometer
```
