### ISSUE TITLE
Consumed Energy only updated every two hours 

### ISSUE THREAD

**Issue by Bl4d3s** [BenPru/luxtronik#293]
Hi,

On both the latest stable and the latest Beta version I experience the following:

Consumed kWh for heating or water is only updated every two hours, other data Like the current energy consumption is updated in real time.
The local webserver shows more frequent updates.

is this expected behavior?
If not what information do you require to debug?

Im a developer so I can change some source code as well to help debugging.

Thanks

**Comment by blue-bean** [comment]
I can confirm this behaviour. It does not depend ob changing the update interval in the config of the plugin.

**Comment by Bl4d3s** [comment]
[config_entry-luxtronik2-01JC7YC0VE8D3E75ASQM9ZW215.json](https://github.com/user-attachments/files/17708109/config_entry-luxtronik2-01JC7YC0VE8D3E75ASQM9ZW215.json)

I have attached the diagnostics below

**Comment by Bl4d3s** [comment]
I figured something out:

The data is not really updated on the socket api, thus the integration is working fine.

I am currently working on building an API for the websocket api, which the web UI itself uses.
I already managed to parse it into structured hierarchical data, 

All thats left, is to map it into the same structure as the current python library to be compatible with. 
I will try to make it an drop-in replacement, if possible. (There the values updates almost in realtime)

**Comment by BenPru** [comment]
> I am currently working on building an API for the websocket api

I also tried this. But the ids are random in the websocket api and it only works with names and they are with a local translation.
Please note that Luxtronik work on another, new API.

**Comment by Bl4d3s** [comment]
I noticed that as well.

My approach would have been to look up what value it is based on the name (providing a list of translations and mapping it based on these values)

Sample:
``` python
temperature_group: list[str] = [
    'Temperaturen'
    'Another translation'
]


def get_property_name(name: str) -> str:
    if name in temperature_group:
        return 'temperatures'
```

Of course this is not ideal, but better than the two hour window screwing over my dashboard with negative power consumption because of the big jumps  ;)

Do you have any more information/timelines in regards towards the new Api?
I must decide, if it would be better to wait for it ^^

**Comment by AJediIAm** [comment]
> > I am currently working on building an API for the websocket api
> 
> I also tried this. But the ids are random in the websocket api and it only works with names and they are with a local translation. Please note that Luxtronik work on another, new API.

Is there any official or unofficial documentation for this new API?
I'm curious to read more about it.

**Comment by Bl4d3s** [comment]
FYI: I managed to get a workaround for the time being. 

My heatpump exposes the current power consumption (albeit only for the total draw, not separate for heating/water), which updates with every pull interval.
I created an helper counting the total consumption based on that, which I then use in the energy dashboard.

the only thing thus missing is the separation of heating / warm water energy draw.

this works for me for now, I think we can close this with the fix being the new api (which hopefully does expose the data).

nevertheless do you know any ETA for the release of that API ? (I would be interested to help implement it)

**Comment by blue-bean** [comment]
> the only thing thus missing is the separation of heating / warm water energy draw.

You can do this by using two template sensors - so you can separate the current power consumption into two sensors:
1. one for hot water: this one is equal to the build-in sensor 'current power consumption' when the WP prepares hot water, otherwise zero
2. one for heating: this one is equal to the build-in sensor 'current power consumption' when the WP is heating, otherwise zero

By using some helper (two integral sensors for calculating the energy using for hot water preparation and heating, and additional counter) you have all you need.

(xxxxxx_xxxx has to be replaced by the number in your installation)


      - name: "Leistung WW"
        unique_id: xxxxxx_xxxx_power_ww
        device_class: power
        unit_of_measurement: "W"
        state: >-
            {% set power = states('sensor.luxtronik_xxxxxx_xxxx_current_power_consumption') | float(0) %}
            {% set mode = states('sensor.luxtronik_xxxxxx_xxxx_status') %}
            {% if power > 0 and mode == "hot water" %}
              {{ states('sensor.luxtronik_xxxxxx_xxxx_current_power_consumption') | float(0) }}
            {% else %}
              {{ 0 }}
            {% endif %}
        
      - name: "Leistung Heizung"
        unique_id: xxxxxx_xxxx_power_heizung
        device_class: power
        unit_of_measurement: "W"
        state: >-
            {% set power = states('sensor.luxtronik_xxxxxx_xxxx_current_power_consumption') | float(0) %}
            {% set mode = states('sensor.luxtronik_xxxxxx_xxxx_status') %}
            {% if power > 0 and mode == "heating" %}
              {{ states('sensor.luxtronik_xxxxxx_xxxx_current_power_consumption') | float(0) }}
            {% else %}
              {{ 0 }}
            {% endif %}

**Comment by s-kurz** [comment]
> By using some helper (two integral sensors for calculating the energy in kWh using for hot water preparation and heating, and the energy counter) you have all you need. PS: in the options of the integral sensors you have to choose a time-based integration (e.g. 30 sec) for unchanged power values.

@blue-bean  I use a similar setup, but to avoid the time-based integration I went with additional triggers instead. One for the startup and two for when the mode changes


```
- trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.luxtronik_xxxxxx_xxxx_current_power_consumption
    - platform: state
      entity_id: sensor.luxtronik_xxxxxx_xxxx_status
      from: heating
    - platform: state
      entity_id: sensor.luxtronik_xxxxxx_xxxx_status
      to: heating
  sensor:
    - name: "Current Power Consumption Heating"
      unique_id: current_power_consumption_heating
      device_class: power
      unit_of_measurement: "W"
      state: >- 
        {% set status = states('sensor.luxtronik_xxxxxx_xxxx_status')  -%} 
        {% if  status == 'heating' -%} {{ states('sensor.luxtronik_xxxxxx_xxxx_current_power_consumption')  | float }} 
        {% else -%} {{ 0 }}
        {% endif -%}
      availability: "{{ is_number( states('sensor.luxtronik_xxxxxx_xxxx_current_power_consumption') ) }}" 
```
