### ISSUE TITLE
write failed ??

### ISSUE THREAD

**Issue by colognebroker** [BenPru/luxtronik#49]
Is there any idea

my service:
service: luxtronik2.write
data:
  parameter: ID_Einst_BWS_akt
  value: "46"

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/luxtronik2/__init__.py:76
Integration: Luxtronik
First occurred: 13:15:42 (11 occurrences)
Last logged: 13:25:38

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'update_immediately_after_write'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1745, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1788, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/luxtronik2/__init__.py", line 76, in write_parameter
    update_immediately_after_write = hass.data[f"{DOMAIN}_conf"][
KeyError: 'update_immediately_after_write'

**Comment by BenPru** [comment]
@colognebroker I think this is a problem with the config data. The current version doesn't create all config keys. In older installations (e.g. my installation) this is no problem. I try to fix it the next days.

By the way you can use the sensor "number.luxtronik2_domestic_water_target_temperature" to write this value.
Yaml service call:
```
service: number.set_value
data:
  value: "46.0"
target:
  entity_id: number.luxtronik2_domestic_water_target_temperature
```

or climate service:
```
service: climate.set_temperature
data:
  temperature: 46.0
target:
  entity_id: climate.luxtronik2_domestic_water
```
